-- RUOLI
CREATE TABLE ruolo (
    id_ruolo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL UNIQUE
);

-- UTENTI
CREATE TABLE utente (
    id_utente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100),
    cognome VARCHAR(100),
    email VARCHAR(150) UNIQUE,
    password VARCHAR(255),
    telefono VARCHAR(20),
    id_ruolo INT DEFAULT 1,
    FOREIGN KEY (id_ruolo) REFERENCES ruolo(id_ruolo)
);

-- VENDITORI
CREATE TABLE venditore (
    id_venditore INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utente INT NULL,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100),
    email VARCHAR(150),
    telefono VARCHAR(20),
    indirizzo VARCHAR(255),
    citta VARCHAR(100),
    provincia VARCHAR(50),
    codice_fiscale VARCHAR(16),
    FOREIGN KEY (id_utente) REFERENCES utente(id_utente)
);

-- ZONE
CREATE TABLE zona (
    cap VARCHAR(10) PRIMARY KEY,
    nome_zona VARCHAR(100),
    prezzo_medio_sqm DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

-- IMMOBILE
CREATE TABLE immobile (
    id_immobile INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venditore INT NOT NULL,  
    tipo VARCHAR(30) DEFAULT 'appartamento',
    indirizzo VARCHAR(255),
    citta VARCHAR(100),
    provincia VARCHAR(50),
    cap VARCHAR(10) NOT NULL,
    metri_quadri DECIMAL(10,2),
    camere INT,
    bagni INT,
    prezzo DECIMAL(12,2),
    descrizione TEXT,
    stato VARCHAR(30) DEFAULT 'abitabile',
    data_inserimento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_venditore) REFERENCES venditore(id_venditore) ON DELETE CASCADE,
    FOREIGN KEY (cap) REFERENCES zona(cap),
    CONSTRAINT chk_immobile_tipo CHECK (tipo IN ('appartamento','villa','ufficio')),
    CONSTRAINT chk_immobile_stato CHECK (stato IN ('ristrutturata','da_ristrutturare','abitabile','nuova'))
);

-- VALUTAZIONE
CREATE TABLE valutazione (
    id_valutazione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_immobile INT NOT NULL,
    id_utente INT NULL,
    stato VARCHAR(30) DEFAULT 'in_corso',
    valore_stimato DECIMAL(12,2),
    valore_calcolato_zona DECIMAL(12,2),
    deadline TIMESTAMP NULL,
    data_richiesta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_completamento TIMESTAMP NULL,
    note TEXT,
    FOREIGN KEY (id_immobile) REFERENCES immobile(id_immobile),
    FOREIGN KEY (id_utente) REFERENCES utente(id_utente),
    CONSTRAINT chk_valutazione_stato CHECK (stato IN ('in_corso','completata','annullata'))
);

-- CONTRATTI
CREATE TABLE contratto (
    id_contratto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_immobile INT NOT NULL,
    id_venditore INT NOT NULL,
    tipo VARCHAR(30),
    esclusiva BOOLEAN DEFAULT TRUE,
    data_inizio DATE NOT NULL,
    data_fine DATE,
    prezzo_finale_minimo DECIMAL(12,2),
    stato VARCHAR(30) DEFAULT 'attivo',
    note TEXT,
    FOREIGN KEY (id_immobile) REFERENCES immobile(id_immobile),
    FOREIGN KEY (id_venditore) REFERENCES venditore(id_venditore),
    CONSTRAINT chk_contratto_stato CHECK (stato IN ('attivo','completato','annullato'))
);
